name: stock-api
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas=1.5.3
  - numpy=1.24.4
  - pip
  - pip:
      - fastapi
      - uvicorn
      - yfinance
      - pandas-ta==0.3.14b0
