services:
  - type: web
    name: stock-strategy-app
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    runtime: python
    region: oregon
    pythonVersion: 3.11.9
